# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go generate ./...
builds:
  - id: keypairs
    main: ./cmd/keypairs/keypairs.go
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      386: i386
      amd64: x86-64
      arm64: aarch64
    format_overrides:
      - goos: windows
        format: zip
env_files:
  github_token: ~/.config/goreleaser/github_token.txt
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
